export interface IDetailProductRes {
  id?: number;
  name?: string;
  slug?: string;
  category?: {
    name?: string;
  }[];
  date_created?: {
    date: string;
    timezone_type: number;
    timezone: string;
  };
  date_modified?: {
    date: string;
    timezone_type: number;
    timezone: string;
  };
  status?: string;
  featuredImage?: string;
  gallrry?: {
    id?: number;
    src?: string;
    name?: string;
  }[];
  featured: boolean;
  catalog_visibility: string;
  description: string;
  short_description: string;
  sku: string;
  price: string;
  regular_price: string;
  sale_price: string;
  date_on_sale_from: null | string;
  date_on_sale_to: null | string;
  total_sales: number;
  tax_status: string;
  tax_class: string;
  manage_stock: boolean;
  stock_quantity: any;
  stock_status: string;
  backorders: string;
  low_stock_amount: string;
  sold_individually: false;
  weight: string;
  length: string;
  width: string;
  height: string;
  upsell_ids: number[];
  cross_sell_ids: number[];
  parent_id: number;
  reviews_allowed: boolean;
  purchase_note: string;
  attributes: string[];
  default_attributes: [];
  menu_order: number;
  post_password: string;
  virtual: false;
  downloadable: boolean;
  category_ids: number[];
  tag_ids: number[];
  shipping_class_id: number;
  downloads: string[];
  image_id: string;
  gallery_image_ids: number[];
  download_limit: number;
  download_expiry: number;
  rating_counts: number[] | string[];
  average_rating: string;
  review_count: number;
  meta_data: string[];
}
